#!/usr/bin/env node
/**
 * Switch apps/mobile/.env between the production (rxnote.ai) and local backends.
 *
 *   node ./scripts/set-env.js prod    # point the app at https://rxnote.ai
 *   node ./scripts/set-env.js local   # point the app at http://localhost:3000
 *
 * EXPO_PUBLIC_* values are inlined into the JS bundle when Metro bundles, so after
 * switching you must (re)start Metro / rebuild for the change to take effect. The npm
 * scripts (env:prod, android:prod, start:prod, …) chain this for you.
 *
 * The Clerk publishable key is a PUBLIC key (safe to embed). `.env` is gitignored.
 */
const fs = require('fs');
const path = require('path');

const ENVS = {
  prod: {
    EXPO_PUBLIC_API_BASE_URL: 'https://rxnote.ai',
    // Production Clerk instance (clerk.rxnote.ai). Requires "Native applications"
    // enabled in the Clerk dashboard for mobile sign-in to work.
    EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_live_Y2xlcmsucnhub3RlLmFpJA',
  },
  local: {
    EXPO_PUBLIC_API_BASE_URL: 'http://localhost:3000',
    EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY:
      'pk_test_YXdhaXRlZC1qZW5uZXQtOC5jbGVyay5hY2NvdW50cy5kZXYk',
  },
};

const target = (process.argv[2] || 'prod').toLowerCase();
const vals = ENVS[target];
if (!vals) {
  console.error(`Unknown env "${target}". Use one of: ${Object.keys(ENVS).join(' | ')}`);
  process.exit(1);
}

const header =
  `# Generated by scripts/set-env.js — target: ${target}\n` +
  `# Do NOT commit. EXPO_PUBLIC_* are inlined into the JS bundle at build/start time.\n`;
const body = Object.entries(vals).map(([k, v]) => `${k}=${v}`).join('\n') + '\n';

fs.writeFileSync(path.join(__dirname, '..', '.env'), header + body);

console.log(`✔ apps/mobile/.env set to "${target}"`);
console.log(`  EXPO_PUBLIC_API_BASE_URL=${vals.EXPO_PUBLIC_API_BASE_URL}`);
console.log(`  EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=${vals.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY.slice(0, 12)}…`);
